sudo: required
language: rust
cache: cargo

addons:
  apt:
    packages:
    - libssl-dev
    
rust:
- stable
- beta
- nightly

matrix:
  fast_finish: true
  allow_failures:
  - rust: nightly

env:
  matrix:
    - FEATURES=""
    - FEATURES="test"
    - FEATURES="termcolor"
    - FEATURES="default"
    - FEATURES="all"

before_cache: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]] && [[ "$FEATURES" == all ]]; then
    cargo install cargo-tarpaulin
  fi

script: |
  case $FEATURES in
    "all")
        cargo test --all --all-features
    ;;
    "default")
        cargo test --all
    ;;
    *)
      cargo test --all --no-default-features --features "$FEATURES"
    esac

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]] && [[ "$FEATURES" == all ]]; then
    cargo tarpaulin --all-features --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
  fi
