language: rust
cache: cargo

rust:
- stable
- beta
- nightly

env:
- FEATURES=""
- FEATURES="test"
- FEATURES="termcolor"
- FEATURES="default"
- FEATURES="all"

jobs:
  include:
  - rust: nightly
    env: MINIMAL_VERSIONS="yes" FEATURES="all"
  allow_failures:
  - rust: nightly

before_cache: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]] && [[ "$FEATURES" == all ]]; then
    cargo install cargo-tarpaulin
  fi

script: |
  case $FEATURES in
    "all")
        if [[ "$MINIMAL_VERSIONS" == yes ]]; then
          cargo test --all --all-features -Z minimal-versions
        else
          cargo test --all --all-features
        fi
    ;;
    "default")
        cargo test --all
    ;;
    *)
      cargo test --all --no-default-features --features "$FEATURES"
    esac

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]] && [[ "$FEATURES" == all ]]; then
    cargo tarpaulin --all-features --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
  fi
